# Generated by Django 4.1.1 on 2022-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('material_info', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
