# Generated by Django 4.1.1 on 2022-09-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.CharField(default='no image added', max_length=100),
        ),
    ]
