# Generated by Django 4.1.1 on 2022-09-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bike_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptype', models.CharField(choices=[('G', 'Gearset'), ('W', 'Wheels'), ('M', 'Miscellaneous')], default='M', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
            ],
        ),
    ]
