# Generated by Django 4.1.1 on 2022-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'accessories',
            },
        ),
    ]
