# Generated by Django 4.1.1 on 2022-09-30 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_bike_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='comptype',
            field=models.CharField(choices=[('G', 'Gearset'), ('W', 'Wheels'), ('M', 'Miscellaneous')], default='M', max_length=1, verbose_name='Component type:'),
        ),
    ]
